export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const SET_ERRORS = "SET_ERRORS";
export const FETCH_CHANNELS = "FETCH_CHANNELS";
export const RESET_CHANNEL = "RESET_CHANNEL";
export const FETCH_MESSAGES = "FETCH_MESSAGES";
export const POST_CHANNEL = "POST_CHANNEL";
export const POST_MESSAGE = "POST_MESSAGE";
export const RESET_MESSAGE = "RESET_MESSAGE";
